database:
    database: trade_pro
    host: postgres
    password: postgres
    port: 5432
    user: postgres
    ref_table: strategy

rabbitmq:
    consumer:
        host: rabbitmq
        login: guest
        password: guest
        port: 5672
        queues:
            trade:
                durable: True
    publisher:
        host: rabbitmq
        login: guest
        password: guest
        port: 5672
