version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - report_calculation_report_bridge
    env_file:
      - .env
    volumes:
      - ./:/app/
      - /app/trade_pro.egg-info/

  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    networks:
      - report_calculation_report_bridge
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - ./rmq/data/:/var/lib/rabbitmq/
      - ./rmq/log/:/var/log/rabbitmq

networks:
  report_calculation_report_bridge:
    external: true
